services:
  shop-with-cart:
    image: fomabb/task-management-system:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db-task-management-system

  db-task-management-system:
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_DB: management_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data: